import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use — AccessEval',
  description: 'Terms and conditions for using the AccessEval accessibility scanning service.',
};

export default function TermsOfUsePage() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4">
      <h1 className="font-display text-display-lg text-ink mb-2">Terms of Use</h1>
      <p className="font-body text-sm text-slate-400 mb-10">Last updated: March 15, 2026</p>

      <div className="prose-legal">
        <p>
          These Terms of Use (&quot;Terms&quot;) govern your use of the AccessEval website
          and accessibility scanning services at accesseval.com (&quot;Service&quot;),
          operated by AccessEval (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By
          using the Service, you agree to these Terms.
        </p>

        <h2>1. Service description</h2>
        <p>
          AccessEval provides automated website accessibility scanning, reporting, and
          compliance monitoring tools. Our Service scans publicly accessible web pages for
          WCAG 2.2 Level AA violations and generates reports with fix instructions. The
          Service is designed for use by administrators of school districts, municipalities,
          libraries, and other government entities.
        </p>

        <h2>2. Accounts</h2>
        <p>
          To access paid features, you must create an account with a valid email address and
          password. You are responsible for maintaining the security of your account
          credentials. You must be at least 18 years of age to create an account. If you
          create an account on behalf of an organization, you represent that you have the
          authority to bind that organization to these Terms.
        </p>

        <h2>3. Free scans</h2>
        <p>
          We offer a free single-page scan that does not require an account. Free scans are
          limited to one scan per URL per 24-hour period. We reserve the right to limit or
          discontinue free scans at any time without notice. Free scan results expire after
          72 hours.
        </p>

        <h2>4. Paid subscriptions</h2>
        <p>
          Paid plans are billed annually through Stripe. Your subscription renews
          automatically unless canceled before the renewal date. You may cancel at any time
          through your account settings or by contacting us. Refunds are handled on a
          case-by-case basis within 30 days of purchase; contact us at
          support@accesseval.com.
        </p>

        <h2>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to scan websites you do not own or have authorization to scan</li>
          <li>Attempt to overwhelm our systems with excessive requests or automated abuse</li>
          <li>Reverse engineer, decompile, or extract our scanning algorithms</li>
          <li>Resell or redistribute scan results as a competing service</li>
          <li>Use the Service for any unlawful purpose</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate accounts that violate these terms.
        </p>

        <h2>6. Scan results and reports</h2>
        <p>
          Accessibility scan results are generated by automated tools (Playwright and
          axe-core) and represent a point-in-time assessment. Our scans identify many common
          accessibility issues but <strong>do not guarantee full WCAG 2.2 AA
          compliance</strong>. Some accessibility issues require manual review by a human
          auditor. Scan results should be used as a guide, not as legal certification of
          compliance.
        </p>
        <p>
          Letter grades, scores, and fix instructions are provided for informational purposes.
          We are not a law firm and do not provide legal advice. If you need legal guidance
          regarding ADA compliance obligations, consult a qualified attorney.
        </p>

        <h2>7. Data ownership</h2>
        <p>
          You retain ownership of any data you provide to us (such as your website URLs and
          account information). We retain ownership of our scan reports, scoring algorithms,
          and fix instruction databases. You may share your scan reports with third parties
          (such as IT vendors or board members) for the purpose of remediating accessibility
          issues.
        </p>

        <h2>8. Website scanning</h2>
        <p>
          Our Service scans only publicly accessible web pages using a standard web browser.
          We do not attempt to access password-protected areas, internal systems, student
          information systems, or any non-public content. We identify ourselves via standard
          HTTP headers during scanning.
        </p>

        <h2>9. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, AccessEval shall not be liable for any
          indirect, incidental, special, consequential, or punitive damages arising from
          your use of the Service. Our total liability for any claim arising from these Terms
          shall not exceed the amount you paid us in the 12 months preceding the claim.
        </p>
        <p>
          We do not guarantee that our Service will identify every accessibility issue on
          your website. We are not liable for any legal action, fines, settlements, or
          penalties related to your website&apos;s accessibility compliance or lack thereof.
        </p>

        <h2>10. Indemnification</h2>
        <p>
          You agree to indemnify and hold AccessEval harmless from any claims, damages, or
          expenses arising from your use of the Service, your violation of these Terms, or
          your scanning of websites you are not authorized to scan.
        </p>

        <h2>11. Service availability</h2>
        <p>
          We strive to maintain high availability but do not guarantee uninterrupted service.
          We may perform maintenance, updates, or modifications to the Service at any time.
          We will make reasonable efforts to notify users of planned downtime.
        </p>

        <h2>12. Changes to these terms</h2>
        <p>
          We may update these Terms from time to time. We will notify registered users of
          material changes via email at least 30 days before the changes take effect.
          Continued use of the Service after changes become effective constitutes acceptance
          of the updated Terms.
        </p>

        <h2>13. Governing law</h2>
        <p>
          These Terms are governed by the laws of the State of Delaware, without regard to
          conflict of law principles. Any disputes arising from these Terms shall be resolved
          in the state or federal courts located in Delaware.
        </p>

        <h2>14. Contact</h2>
        <p>
          Questions about these Terms? Contact us at{' '}
          <a href="mailto:support@accesseval.com">support@accesseval.com</a>.
        </p>
      </div>
    </div>
  );
}
