FROM mcr.microsoft.com/playwright:v1.58.0-noble

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npx prisma generate

ENV NODE_ENV=production

CMD ["npx", "tsx", "worker/index.ts"]
