import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11 },
  header: { marginBottom: 20 },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 12, color: '#666' },
  grade: { fontSize: 72, fontWeight: 'bold', textAlign: 'center', marginVertical: 20 },
  scoreText: { fontSize: 16, textAlign: 'center', color: '#666', marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 8, borderBottom: '1 solid #ddd', paddingBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  label: { color: '#666' },
  value: { fontWeight: 'bold' },
  issueItem: { marginBottom: 6, paddingLeft: 8, borderLeft: '2 solid #ddd' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 9, color: '#999', textAlign: 'center' },
});

interface BoardReportProps {
  orgName: string;
  siteUrl: string;
  reportDate: string;
  grade: string;
  score: number;
  criticalCount: number;
  majorCount: number;
  minorCount: number;
  issuesFixed: number;
  topIssues: { description: string; severity: string; wcag: string | null }[];
  pdfCount: number;
  hasStatement: boolean;
}

export function BoardReport(props: BoardReportProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{props.orgName}</Text>
          <Text style={styles.subtitle}>Website Accessibility Report — {props.reportDate}</Text>
          <Text style={styles.subtitle}>{props.siteUrl}</Text>
        </View>

        <Text style={styles.grade}>{props.grade}</Text>
        <Text style={styles.scoreText}>Accessibility Score: {props.score}/100</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Issue Summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Critical issues</Text>
            <Text style={styles.value}>{props.criticalCount}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Major issues</Text>
            <Text style={styles.value}>{props.majorCount}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Minor issues</Text>
            <Text style={styles.value}>{props.minorCount}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Issues fixed since last report</Text>
            <Text style={styles.value}>{props.issuesFixed}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Top Remaining Issues</Text>
          {props.topIssues.map((issue, i) => (
            <View key={i} style={styles.issueItem}>
              <Text>{issue.severity.toUpperCase()}: {issue.description}</Text>
              {issue.wcag && <Text style={styles.label}>WCAG {issue.wcag}</Text>}
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Additional Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>PDFs requiring review</Text>
            <Text style={styles.value}>{props.pdfCount}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Accessibility statement published</Text>
            <Text style={styles.value}>{props.hasStatement ? 'Yes' : 'No'}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Generated by AccessEval — accesseval.com</Text>
      </Page>
    </Document>
  );
}
