import { prisma } from '@/lib/db';
import { notFound } from 'next/navigation';

export default async function SharedReportPage({ params }: { params: { token: string } }) {
  const shareLink = await prisma.shareLink.findUnique({
    where: { token: params.token },
    include: {
      scan: {
        include: {
          site: { include: { organization: true } },
          pages: { orderBy: { issueCount: 'desc' }, take: 20 },
          issues: { orderBy: [{ severity: 'asc' }], take: 50 },
        },
      },
    },
  });

  if (!shareLink) notFound();
  if (shareLink.expiresAt && shareLink.expiresAt < new Date()) notFound();

  const { scan } = shareLink;
  const gradeColor = (scan.score || 0) >= 80 ? 'text-green-600'
    : (scan.score || 0) >= 60 ? 'text-yellow-600' : 'text-red-600';

  return (
    <div className="max-w-3xl mx-auto py-12 px-6">
      <h1 className="text-2xl font-bold mb-1">{scan.site.organization.name}</h1>
      <p className="text-gray-500 mb-8">{scan.site.url} — Scanned {scan.completedAt?.toLocaleDateString()}</p>

      <div className="text-center mb-8 p-8 bg-gray-50 rounded-xl">
        <div className={`text-7xl font-bold ${gradeColor}`}>{scan.grade}</div>
        <div className="text-xl text-gray-600 mt-2">{scan.score}/100</div>
      </div>

      <div className="grid grid-cols-3 gap-4 mb-8">
        <div className="text-center p-4 bg-red-50 rounded-lg">
          <div className="text-2xl font-bold text-red-600">{scan.criticalCount}</div>
          <div className="text-sm">Critical</div>
        </div>
        <div className="text-center p-4 bg-yellow-50 rounded-lg">
          <div className="text-2xl font-bold text-yellow-600">{scan.majorCount}</div>
          <div className="text-sm">Major</div>
        </div>
        <div className="text-center p-4 bg-blue-50 rounded-lg">
          <div className="text-2xl font-bold text-blue-600">{scan.minorCount}</div>
          <div className="text-sm">Minor</div>
        </div>
      </div>

      <h2 className="font-semibold text-lg mb-4">Top Issues</h2>
      <div className="space-y-3 mb-8">
        {scan.issues.map((issue) => (
          <div key={issue.id} className="border rounded-lg p-4">
            <div className="flex items-center gap-2 mb-1">
              <span className={`text-xs font-medium px-2 py-0.5 rounded ${
                issue.severity === 'critical' ? 'bg-red-100 text-red-700'
                : issue.severity === 'major' ? 'bg-yellow-100 text-yellow-700'
                : 'bg-blue-100 text-blue-700'
              }`}>{issue.severity}</span>
            </div>
            <p className="text-sm">{issue.description}</p>
          </div>
        ))}
      </div>

      <p className="text-xs text-gray-400 text-center">
        Report generated by <a href="https://accesseval.com" className="text-blue-600">AccessEval</a>
      </p>
    </div>
  );
}
